steps:
  # Step 1: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-f',
        'Dockerfile',
        '-t',
        'asia-south1-docker.pkg.dev/ai0015455-sfa-test/ccc-sfa-test-cloudrun-main-backend/frontend-app:latest',
        '.'
      ]

  # Step 2: Push image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'asia-south1-docker.pkg.dev/ai0015455-sfa-test/ccc-sfa-test-cloudrun-main-backend/frontend-app:latest'
      ]

  # Step 3: Deploy to Cloud Run with secrets
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'run',
        'deploy',
        'tccc-sfa-test-cloudrun-front-end',
        '--image=asia-south1-docker.pkg.dev/ai0015455-sfa-test/ccc-sfa-test-cloudrun-main-backend/frontend-app:latest',
        '--region=asia-south1',
        '--platform=managed',
        '--execution-environment=gen2',
        '--allow-unauthenticated',
        '--service-account=tccc-sfa-test-cloudrun-sa@ai0015455-sfa-test.iam.gserviceaccount.com',
        '--vpc-egress=all',
        '--min-instances=1',
        '--max-instances=3',
        '--cpu=1',
        '--memory=512Mi',
        '--set-secrets=NEXT_PUBLIC_API_URL=NEXT_PUBLIC_API_URL:latest,NEXT_PUBLIC_STRAPI_API_URL=NEXT_PUBLIC_STRAPI_API_URL:latest,NEXT_PUBLIC_GLUEDIN_API_KEY=NEXT_PUBLIC_GLUEDIN_API_KEY:latest,NEXT_PUBLIC_GLUEDIN_SECRET_KEY=NEXT_PUBLIC_GLUEDIN_SECRET_KEY:latest,NEXT_PUBLIC_SECRET_KEY=NEXT_PUBLIC_SECRET_KEY:latest,NEXT_PUBLIC_GA_ID=NEXT_PUBLIC_GA_ID:latest,NEXT_PUBLIC_FIREBASE_API_KEY=NEXT_PUBLIC_FIREBASE_API_KEY:latest,NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN:latest,NEXT_PUBLIC_FIREBASE_PROJECT_ID=NEXT_PUBLIC_FIREBASE_PROJECT_ID:latest,NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET:latest,NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID:latest,NEXT_PUBLIC_FIREBASE_APP_ID=NEXT_PUBLIC_FIREBASE_APP_ID:latest,NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID=NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID:latest,NEXT_PUBLIC_FIREBASE_VAPID_KEY=NEXT_PUBLIC_FIREBASE_VAPID_KEY:latest,NEXT_PUBLIC_INFOBIP_WHATSAPP_URL=NEXT_PUBLIC_INFOBIP_WHATSAPP_URL:latest,NEXT_PUBLIC_CDP_CLIENT_ID=NEXT_PUBLIC_CDP_CLIENT_ID:latest,NEXT_PUBLIC_CDP_BRAND_NAME=NEXT_PUBLIC_CDP_BRAND_NAME:latest,NEXT_PUBLIC_CDP_API_URL=NEXT_PUBLIC_CDP_API_URL:latest,NEXT_PUBLIC_CDP_API_KEY=NEXT_PUBLIC_CDP_API_KEY:latest,NEXT_PUBLIC_CDP_USER_IDENTIFIED_TYPE=NEXT_PUBLIC_CDP_USER_IDENTIFIED_TYPE:latest,NEXT_PUBLIC_CDP_USER_IDENTIFIER_SUB_TYPE=NEXT_PUBLIC_CDP_USER_IDENTIFIER_SUB_TYPE:latest,NEXT_PUBLIC_IP_URL=NEXT_PUBLIC_IP_URL:latest'
      ]

images:
  - asia-south1-docker.pkg.dev/ai0015455-sfa-test/ccc-sfa-test-cloudrun-main-backend/frontend-app:latest

options:
  logging: CLOUD_LOGGING_ONLY
