import { GluedInActivityTimeline } from './methods/activityTimeline';
import { GluedInSDKInitilize } from './methods/intilizeSDK';
import { GluedInAuthModule } from './methods/authModule';
import { GluedInUserModule } from './methods/userModule';
import { GluedInCuratedContentModule } from './methods/curatedContent';
import { GluedInFeedModule } from './methods/feedModule';
import { GluedInHashTag } from './methods/hashtag';
import { GluedInChallenges } from './methods/challenges';
import { GluedInDiscover } from './methods/discover';
import { GluedInNotificationModule } from './methods/notification';
import { GluedInRewardsModule } from './methods/rewardsModule';
import { GluedInVideosModule } from './methods/videosModule';
declare const _default: {
    GluedInActivityTimeline: typeof GluedInActivityTimeline;
    GluedInSDKInitilize: typeof GluedInSDKInitilize;
    GluedInAuthModule: typeof GluedInAuthModule;
    GluedInUserModule: typeof GluedInUserModule;
    GluedInCuratedContentModule: typeof GluedInCuratedContentModule;
    GluedInFeedModule: typeof GluedInFeedModule;
    GluedInHashTag: typeof GluedInHashTag;
    GluedInChallenges: typeof GluedInChallenges;
    GluedInDiscover: typeof GluedInDiscover;
    GluedInNotificationModule: typeof GluedInNotificationModule;
    GluedInRewardsModule: typeof GluedInRewardsModule;
    GluedInVideosModule: typeof GluedInVideosModule;
};
export default _default;
