export type TCMSResponse ={
  data: {
    id: number;
    documentId: string;
    scroll_and_lol_heading: string;
    view_all_button_text: string | null;
    suprise_me_text: string | null;
    pick_your_mood_text: string | null;
    pick_your_mood_sub_heading: string | null;
    joke_box_heading: string | null;
    joke_box_subheading: string | null;
    latest_button_text: string | null;
    trending_button_text: string | null;
    joke_disclamer_text: string | null;
    socials_text: string | null;
    explore_button_text: string | null;
    scroll_and_lol_text: string | null;
    pj_challenge_text: string | null;
    joke_box_text: string | null;
    hall_of_lame_text: string | null;
    refer_friend_text: string | null;
    invite_code_text: string | null;
    nav_banner_heading: string | null;
    nav_banner_subheading: string | null;
    contest_button_text: string | null;
    whatsapp_chat_text: string | null;
    home_text: string | null;
    need_help_heading: string | null;
    faq_text: string | null;
    terms_and_conditions_text: string | null;
    sitemap_text: string | null;
    privacy_policy_text: string | null;
    terms_and_condition_line_desktop: string | null;
    terms_and_condition_line_mobile: string | null;
    contact_us_text: string | null;
    logout_text: string | null;
    profile_text: string | null;
    comic_coin_text: string | null;
    profile_text_mobile: string | null;
    refresh_ring_text: string | null;
    previous_winner_text: string | null;
    leaderboard_text: string | null;
    notification_heading: string | null;
    notification_sub_heading: string | null;
    refer_a_friend_text: string | null;
    refer_now_text: string | null;
    address_text: string | null;
    add_button_text: string | null;
    help_us_heading: string | null;
    address_popup_heading: string | null;
    address_line_1_placeholder: string | null;
    address_line_2_placeholder: string | null;
    nearest_landmark_placeholder: string | null;
    alternative_number_placeholder: string | null;
    pincode_placeholder: string | null;
    state_placeholder: string | null;
    city_placeholder: string | null;
    set_as_default_text: string | null;
    save_address_button_text: string | null;
    rank_text: string | null;
    next_button_text: string | null;
    previous_button_text: string | null;
    new_rewards_text: string | null;
    previous_winner_list_text: string | null;
    submit_joke_heading: string | null;
    submit_joke_subheading: string | null;
    select_language_text: string | null;
    title_text: string | null;
    joke_submit_consent_paragraph: string | null;
    category_heading: string | null;
    joke_title_placeholder: string | null;
    joke_title_limit: string | null;
    upload_text: string | null;
    upload_subheading: string | null;
    submit_button_text: string | null;
    form_condition_text: string | null;
    text_type_joke_heading: string | null;
    createdAt: string;
    updatedAt: string;
    publishedAt: string;
    locale: string;
    pj_banner_text: string | null;
    pj_banner_subheading: string | null;
    pj_banner_submit_button_text: string | null;
  };
  meta: Record<string, unknown>;
}
