const API_URL = process.env.NEXT_PUBLIC_API_URL;
const AVATARS_URL = process.env.NEXT_PUBLIC_AVATARS_URL;
const GLUEDIN_API_KEY = process.env.NEXT_PUBLIC_GLUEDIN_API_KEY;
const GLUEDIN_SECRET_KEY = process.env.NEXT_PUBLIC_GLUEDIN_SECRET_KEY;
const SECRET_KEY = process.env.NEXT_PUBLIC_SECRET_KEY;
const GA_ID = process.env.NEXT_PUBLIC_GA_ID;

export {
  API_URL,
  AVATARS_URL,
  GLUEDIN_API_KEY,
  GLUEDIN_SECRET_KEY,
  SECRET_KEY,
  GA_ID,
};
